[package]
name = "tiny-serve"
version = "0.1.0"
authors = ["Thomas Paul Roberts"]
edition = "2021"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "tiny-serve"

[dependencies]
tiny_http = "0.12"
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
